@baseUrl = https://api.github.com
@token = REDACTED
@acceptHeader = application/vnd.github+json
@readmeAcceptHeader = application/vnd.github.v3.html+json


GET {{baseUrl}}/user/starred
    ?page=1
Authorization: token {{token}}
Accept: {{acceptHeader}}

###

GET {{baseUrl}}/search/repositories
    ?q=flutter
    &page=1
Authorization: token {{token}}
Accept: {{acceptHeader}}

###
GET {{baseUrl}}/repos/flutter/flutter/readme
Authorization: token {{token}}
Accept: {{readmeAcceptHeader}}

###

PUT {{baseUrl}}/user/starred/hashicorp/terraform
Authorization: token {{token}}
Accept: {{acceptHeader}}
Content-Length: 0

###
DELETE  {{baseUrl}}/user/starred/hashicorp/terraform
Authorization: token {{token}}
Accept: {{acceptHeader}}

